# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: 2.15.0
repos:
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-format
    args:
    - --no-diff
    - -i
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
    stages: [pre-commit]
  - id: pretty-format-toml
    args: [--autofix]
    stages: [pre-commit]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
  - id: black
- repo: local
  hooks:
  - id: unit-test
    name: unit tests
    description: Run unit tests.
    entry: just test
    language: system
    types_or: [c++, c, toml, cmake]
    pass_filenames: false
    stages: [pre-commit]
