name: unit-test

on: push

jobs:
  examples:
    name: ${{ matrix.os }}-${{ matrix.compiler }}-${{matrix.build_type}}-${{ matrix.generator }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        compiler:
        - gcc
        - llvm
        generator:
        - default
        build_type:
        - Debug
        - Release
        include:
        - {os: windows-latest, build_type: Debug, compiler: gcc, generator: Ninja}
        - {os: windows-latest, build_type: Debug, compiler: msvc, generator: default}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - uses: extractions/setup-just@v2
    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}
        vcvarsall: ${{ contains(matrix.os, 'windows' )}}
        cmake: true
        ninja: true
        vcpkg: true
        ccache: true
        clangtidy: true
        cppcheck: true
        gcovr: true
        opencppcoverage: true
    - name: Build Targets
      run: just test
    - uses: actions/upload-artifact@v4
      with:
        name: build-${{matrix.os}}-${{matrix.build_type}}-${{matrix.compiler}}
        path: ./build/
