name: unit-test

on: push

jobs:
  examples:
    name: ${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.generator }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        compiler:
        - gcc
        - llvm
        generator:
        - default
        build_type:
        - Debug
        include:
        - {os: windows-latest, compiler: gcc, generator: Ninja}
        - {os: windows-latest, compiler: msvc, generator: default}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - uses: extractions/setup-just@v2
    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}
        vcvarsall: ${{ contains(matrix.os, 'windows' )}}
        cmake: true
        ninja: true
        vcpkg: true
        ccache: true
        clangtidy: true
        cppcheck: true
        gcovr: true
        opencppcoverage: true
    - name: Build Targets
      run: just ccmake test

    - name: Unix - Test and coverage
      if: runner.os != 'Windows'
      working-directory: ./build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ctest -C ${{matrix.build_type}}
        gcovr -j ${{env.nproc}} --delete --root ../ --print-summary --xml-pretty --xml coverage.xml . --gcov-executable '${{ matrix.gcov_executable }}'

    - name: Windows - Test and coverage
      if: runner.os == 'Windows'
      working-directory: ./build
      run: |
        OpenCppCoverage.exe --export_type cobertura:coverage.xml --cover_children -- ctest -C ${{matrix.build_type}}

    - name: Publish to codecov
      uses: codecov/codecov-action@v2
      with:
        flags: ${{ runner.os }}
        name: ${{ runner.os }}-coverage
        files: ./build/coverage.xml
